<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="SeedData\seed-carrera.json" />
    <Content Remove="SeedData\seed-empresa.json" />
    <Content Remove="SeedData\seed-escuela.json" />
    <Content Remove="SeedData\seed-facultad.json" />
    <Content Remove="SeedData\seed-modalidadtrabajo.json" />
    <Content Remove="SeedData\seed-roles.json" />
    <Content Remove="SeedData\seed-tipocontrato.json" />
    <Content Remove="SeedData\seed-tipoformacion.json" />
    <Content Remove="SeedData\seed-users.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="SeedData\seed-carrera.json" />
    <None Include="SeedData\seed-empresa.json" />
    <None Include="SeedData\seed-escuela.json" />
    <None Include="SeedData\seed-facultad.json" />
    <None Include="SeedData\seed-modalidadtrabajo.json" />
    <None Include="SeedData\seed-roles.json" />
    <None Include="SeedData\seed-tipocontrato.json" />
    <None Include="SeedData\seed-tipoformacion.json" />
    <None Include="SeedData\seed-users.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.1" />
  </ItemGroup>

</Project>
