// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SiseApi.Data;

#nullable disable

namespace SiseApi.Migrations
{
    [DbContext(typeof(SiseDbContext))]
    partial class SiseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SiseApi.Models.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("SiseApi.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SiseApi.Models.Auditoria", b =>
                {
                    b.Property<int>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idAuditoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAuditoria"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("accion");

                    b.Property<string>("ColumnaAfectada")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("columnaAfectada");

                    b.Property<DateTime>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fechaHora")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.Property<string>("TablaAfectada")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tablaAfectada");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("valorAnterior");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("valorNuevo");

                    b.HasKey("IdAuditoria");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("SiseApi.Models.Carrera", b =>
                {
                    b.Property<int>("IdCarrera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCarrera");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarrera"));

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<int>("IdEscuela")
                        .HasColumnType("int")
                        .HasColumnName("idEscuela");

                    b.Property<string>("NombreCarrera")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombreCarrera");

                    b.HasKey("IdCarrera");

                    b.HasIndex("IdEscuela");

                    b.ToTable("Carrera");
                });

            modelBuilder.Entity("SiseApi.Models.Egresado", b =>
                {
                    b.Property<int>("IdEgresado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idEgresado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEgresado"));

                    b.Property<int>("AñoEgreso")
                        .HasColumnType("int")
                        .HasColumnName("añoEgreso");

                    b.Property<string>("CodigoUniversitario")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("codigoUniversitario");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<int>("IdCarrera")
                        .HasColumnType("int")
                        .HasColumnName("idCarrera");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("idPersona");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.HasKey("IdEgresado");

                    b.HasIndex("IdCarrera");

                    b.HasIndex("IdPersona");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Egresado");
                });

            modelBuilder.Entity("SiseApi.Models.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idEmpresa");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpresa"));

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("correo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("direccion");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("razonSocial");

                    b.Property<string>("Ruc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .HasColumnName("ruc")
                        .IsFixedLength();

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("telefono");

                    b.HasKey("IdEmpresa");

                    b.HasIndex(new[] { "Ruc" }, "UQ__Empresa__C2B74E61241D7335")
                        .IsUnique();

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("SiseApi.Models.Escuela", b =>
                {
                    b.Property<int>("IdEscuela")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idEscuela");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEscuela"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<int>("IdFacultad")
                        .HasColumnType("int")
                        .HasColumnName("idFacultad");

                    b.Property<string>("NombreEscuela")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombreEscuela");

                    b.HasKey("IdEscuela");

                    b.HasIndex("IdFacultad");

                    b.ToTable("Escuela");
                });

            modelBuilder.Entity("SiseApi.Models.ExperienciaLaboral", b =>
                {
                    b.Property<int>("IdExperiencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idExperiencia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdExperiencia"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("cargo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("empresa");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fechaFin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fechaInicio");

                    b.Property<int>("IdEgresado")
                        .HasColumnType("int")
                        .HasColumnName("idEgresado");

                    b.HasKey("IdExperiencia");

                    b.HasIndex("IdEgresado");

                    b.ToTable("ExperienciaLaboral");
                });

            modelBuilder.Entity("SiseApi.Models.Facultad", b =>
                {
                    b.Property<int>("IdFacultad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idFacultad");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFacultad"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<string>("NombreFacultad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombreFacultad");

                    b.HasKey("IdFacultad");

                    b.ToTable("Facultad");
                });

            modelBuilder.Entity("SiseApi.Models.FormacionComplementaria", b =>
                {
                    b.Property<int>("IdFormacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idFormacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFormacion"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fechaFin");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fechaInicio");

                    b.Property<int>("IdEgresado")
                        .HasColumnType("int")
                        .HasColumnName("idEgresado");

                    b.Property<int>("IdTipoFormacion")
                        .HasColumnType("int")
                        .HasColumnName("idTipoFormacion");

                    b.Property<string>("Institucion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("institucion");

                    b.Property<string>("NombreDelCurso")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombreDelCurso");

                    b.HasKey("IdFormacion");

                    b.HasIndex("IdEgresado");

                    b.HasIndex("IdTipoFormacion");

                    b.ToTable("FormacionesComplementarias");
                });

            modelBuilder.Entity("SiseApi.Models.ModalidadTrabajo", b =>
                {
                    b.Property<int>("IdModalidadTrabajo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idModalidadTrabajo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModalidadTrabajo"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<string>("NombreModalidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombreModalidad");

                    b.HasKey("IdModalidadTrabajo");

                    b.HasIndex(new[] { "NombreModalidad" }, "UQ__Modalida__5DEA366D6F69E6E5")
                        .IsUnique();

                    b.ToTable("ModalidadTrabajo");
                });

            modelBuilder.Entity("SiseApi.Models.OfertaLaboral", b =>
                {
                    b.Property<int>("IdOferta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idOferta");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOferta"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaCierre")
                        .HasColumnType("date")
                        .HasColumnName("fechaCierre");

                    b.Property<DateOnly>("FechaPublicacion")
                        .HasColumnType("date")
                        .HasColumnName("fechaPublicacion");

                    b.Property<int?>("IdEgresadoGanador")
                        .HasColumnType("int")
                        .HasColumnName("idEgresadoGanador");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("idEmpresa");

                    b.Property<int>("IdModalidadTrabajo")
                        .HasColumnType("int")
                        .HasColumnName("idModalidadTrabajo");

                    b.Property<int>("IdTipoContrato")
                        .HasColumnType("int")
                        .HasColumnName("idTipoContrato");

                    b.Property<string>("Requisitos")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("requisitos");

                    b.Property<decimal?>("Sueldo")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("sueldo");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("titulo");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("ubicacion");

                    b.HasKey("IdOferta");

                    b.HasIndex("IdEgresadoGanador");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdModalidadTrabajo");

                    b.HasIndex("IdTipoContrato");

                    b.ToTable("OfertaLaboral");
                });

            modelBuilder.Entity("SiseApi.Models.Persona", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idPersona");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPersona"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("apellidoMaterno");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("apellidoPaterno");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("correo");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("dni");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("telefono");

                    b.HasKey("IdPersona");

                    b.HasIndex("IdUsuario")
                        .IsUnique()
                        .HasFilter("[idUsuario] IS NOT NULL");

                    b.HasIndex(new[] { "Dni" }, "UQ__Persona__D87608A7915FF7BB")
                        .IsUnique();

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("SiseApi.Models.Representante", b =>
                {
                    b.Property<int>("IdRepresentante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idRepresentante");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRepresentante"));

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cargo");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("idEmpresa");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int")
                        .HasColumnName("idPersona");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("idUsuario");

                    b.HasKey("IdRepresentante");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdPersona");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Representante");
                });

            modelBuilder.Entity("SiseApi.Models.TipoContrato", b =>
                {
                    b.Property<int>("IdTipoContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTipoContrato");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoContrato"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<string>("NombreTipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombreTipo");

                    b.HasKey("IdTipoContrato");

                    b.HasIndex(new[] { "NombreTipo" }, "UQ__TipoCont__634171E76788CD20")
                        .IsUnique();

                    b.ToTable("TipoContrato");
                });

            modelBuilder.Entity("SiseApi.Models.TipoFormacion", b =>
                {
                    b.Property<int>("IdTipoFormacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idTipoFormacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoFormacion"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<string>("NombreTipoFormacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombreTipoFormacion");

                    b.HasKey("IdTipoFormacion");

                    b.ToTable("TipoFormacion");
                });

            modelBuilder.Entity("SiseApi.Models.VwOfertasDisponible", b =>
                {
                    b.Property<int?>("DiasRestantes")
                        .HasColumnType("int")
                        .HasColumnName("diasRestantes");

                    b.Property<string>("Empresa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("empresa");

                    b.Property<DateOnly>("FechaCierre")
                        .HasColumnType("date")
                        .HasColumnName("fechaCierre");

                    b.Property<int>("IdOferta")
                        .HasColumnType("int")
                        .HasColumnName("idOferta");

                    b.Property<string>("NombreModalidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombreModalidad");

                    b.Property<decimal?>("Sueldo")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("sueldo");

                    b.Property<string>("TipoContrato")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tipoContrato");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("titulo");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("ubicacion");

                    b.ToTable((string)null);

                    b.ToView("vwOfertasDisponibles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("SiseApi.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("SiseApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("SiseApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("SiseApi.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiseApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("SiseApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SiseApi.Models.Auditoria", b =>
                {
                    b.HasOne("SiseApi.Models.ApplicationUser", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK_Auditoria_Usuario_Identity");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SiseApi.Models.Carrera", b =>
                {
                    b.HasOne("SiseApi.Models.Escuela", "IdEscuelaNavigation")
                        .WithMany("Carreras")
                        .HasForeignKey("IdEscuela")
                        .IsRequired()
                        .HasConstraintName("FK_Carrera_Escuela");

                    b.Navigation("IdEscuelaNavigation");
                });

            modelBuilder.Entity("SiseApi.Models.Egresado", b =>
                {
                    b.HasOne("SiseApi.Models.Carrera", "Carrera")
                        .WithMany("Egresados")
                        .HasForeignKey("IdCarrera")
                        .IsRequired()
                        .HasConstraintName("FK_Egresado_Carrera");

                    b.HasOne("SiseApi.Models.Persona", "Persona")
                        .WithMany("Egresados")
                        .HasForeignKey("IdPersona")
                        .IsRequired()
                        .HasConstraintName("FK_Egresado_Persona");

                    b.HasOne("SiseApi.Models.ApplicationUser", "Usuario")
                        .WithMany("Egresados")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("Persona");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SiseApi.Models.Escuela", b =>
                {
                    b.HasOne("SiseApi.Models.Facultad", "IdFacultadNavigation")
                        .WithMany("Escuelas")
                        .HasForeignKey("IdFacultad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdFacultadNavigation");
                });

            modelBuilder.Entity("SiseApi.Models.ExperienciaLaboral", b =>
                {
                    b.HasOne("SiseApi.Models.Egresado", "IdEgresadoNavigation")
                        .WithMany("ExperienciaLaborals")
                        .HasForeignKey("IdEgresado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdEgresadoNavigation");
                });

            modelBuilder.Entity("SiseApi.Models.FormacionComplementaria", b =>
                {
                    b.HasOne("SiseApi.Models.Egresado", "IdEgresadoNavigation")
                        .WithMany("FormacionComplementaria")
                        .HasForeignKey("IdEgresado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiseApi.Models.TipoFormacion", "IdTipoFormacionNavigation")
                        .WithMany("FormacionComplementaria")
                        .HasForeignKey("IdTipoFormacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdEgresadoNavigation");

                    b.Navigation("IdTipoFormacionNavigation");
                });

            modelBuilder.Entity("SiseApi.Models.OfertaLaboral", b =>
                {
                    b.HasOne("SiseApi.Models.Egresado", "IdEgresadoGanadorNavigation")
                        .WithMany("OfertaLaborals")
                        .HasForeignKey("IdEgresadoGanador");

                    b.HasOne("SiseApi.Models.Empresa", "IdEmpresaNavigation")
                        .WithMany("OfertaLaborals")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiseApi.Models.ModalidadTrabajo", "IdModalidadTrabajoNavigation")
                        .WithMany("OfertaLaborals")
                        .HasForeignKey("IdModalidadTrabajo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SiseApi.Models.TipoContrato", "IdTipoContratoNavigation")
                        .WithMany("OfertaLaborals")
                        .HasForeignKey("IdTipoContrato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdEgresadoGanadorNavigation");

                    b.Navigation("IdEmpresaNavigation");

                    b.Navigation("IdModalidadTrabajoNavigation");

                    b.Navigation("IdTipoContratoNavigation");
                });

            modelBuilder.Entity("SiseApi.Models.Persona", b =>
                {
                    b.HasOne("SiseApi.Models.ApplicationUser", "Usuario")
                        .WithOne("Persona")
                        .HasForeignKey("SiseApi.Models.Persona", "IdUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SiseApi.Models.Representante", b =>
                {
                    b.HasOne("SiseApi.Models.Empresa", "IdEmpresaNavigation")
                        .WithMany("Representantes")
                        .HasForeignKey("IdEmpresa")
                        .IsRequired()
                        .HasConstraintName("FK_Representante_Empresa");

                    b.HasOne("SiseApi.Models.Persona", "IdPersonaNavigation")
                        .WithMany("Representantes")
                        .HasForeignKey("IdPersona")
                        .IsRequired()
                        .HasConstraintName("FK_Representante_Persona");

                    b.HasOne("SiseApi.Models.ApplicationUser", "Usuario")
                        .WithMany("Representantes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdEmpresaNavigation");

                    b.Navigation("IdPersonaNavigation");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SiseApi.Models.ApplicationUser", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("Egresados");

                    b.Navigation("Persona");

                    b.Navigation("Representantes");
                });

            modelBuilder.Entity("SiseApi.Models.Carrera", b =>
                {
                    b.Navigation("Egresados");
                });

            modelBuilder.Entity("SiseApi.Models.Egresado", b =>
                {
                    b.Navigation("ExperienciaLaborals");

                    b.Navigation("FormacionComplementaria");

                    b.Navigation("OfertaLaborals");
                });

            modelBuilder.Entity("SiseApi.Models.Empresa", b =>
                {
                    b.Navigation("OfertaLaborals");

                    b.Navigation("Representantes");
                });

            modelBuilder.Entity("SiseApi.Models.Escuela", b =>
                {
                    b.Navigation("Carreras");
                });

            modelBuilder.Entity("SiseApi.Models.Facultad", b =>
                {
                    b.Navigation("Escuelas");
                });

            modelBuilder.Entity("SiseApi.Models.ModalidadTrabajo", b =>
                {
                    b.Navigation("OfertaLaborals");
                });

            modelBuilder.Entity("SiseApi.Models.Persona", b =>
                {
                    b.Navigation("Egresados");

                    b.Navigation("Representantes");
                });

            modelBuilder.Entity("SiseApi.Models.TipoContrato", b =>
                {
                    b.Navigation("OfertaLaborals");
                });

            modelBuilder.Entity("SiseApi.Models.TipoFormacion", b =>
                {
                    b.Navigation("FormacionComplementaria");
                });
#pragma warning restore 612, 618
        }
    }
}
